name: Build and Test opentelemetry-cpp

on:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cmake_test:
    name: CMake test (without otlp-exporter)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-ppc64le]

    steps:
      - name: Checkout opentelemetry-cpp repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Environment
        env:
          CC: /usr/bin/gcc-10
          CXX: /usr/bin/g++-10
        run: |
          sudo -E ./ci/setup_googletest.sh
          sudo -E ./ci/setup_ci_environment.sh

      - name: Run CMake Tests (without otlp-exporter)
        env:
          CC: /usr/bin/gcc-10
          CXX: /usr/bin/g++-10
        run: |
          ./ci/do_ci.sh cmake.test
